# Generated by Django 4.2.1 on 2023-08-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polo_Amazontech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('consumo', models.CharField(max_length=255)),
                ('protocolo', models.CharField(max_length=1000)),
            ],
        ),
    ]
